
export const ICON_ALT = "icon"
export const ICON_COMPONENT = "icon-component"
export const DARK_MODE_TOGGLE_COMPONENT = "dark-mode-toggle"
export const HERO_SECTION_IMAGE = 'Hero-Section-Image'
export const RESUME_LINK = 'https://drive.google.com/file/d/1g2nixuB5uN75RlNYVRAaAcbNL9Kuvqkh/view?usp=sharing'
export const ICON_COMPONENT_HOME = "icon-component-home"
export const SOCIAL_MEDIA_COMPONENT = "social-medial-icons"
export const MUI_CHIP = "mui-chip"
export const FULL_STACK_DEV = "<b>Full-Stack Developer</b>"
export const ABOUT_DESC =  `🚀 I am a ${FULL_STACK_DEV} with hands-on experience in building robust and scalable web applications.I am always open to collaboration and creating amazing digital experiences; Let's connect and explore the possibilities together;`
export const ABOUT_SUB_DESC = "Passionate software engineer working at a dynamic startup, with expertise in a variety of cutting-edge technologies and tools; My skills include;"
export const ABOUT_SUB_FOOTER_DESC = " Let's connect, collaborate, and work together! 🌟;"
export const ABOUT_COMPONENT = "about-component"
export const ICON_ABOUT_ALT = "about-image"
export const NAME_ANIMATION = "name-animation-test-id"
export const EDUIMG_1 = "https://mintbook.com/blog/wp-content/uploads/2019/09/Top-10-Secrets-to-Improve-Learning-Skills-min.png"
export const EDUIMG_2 = "https://upload.wikimedia.org/wikipedia/commons/e/ed/Wikimedia_in_Education_illustration_classroom.svg"
export const EDUIMG_3 = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Wikimedia_in_Education_illustration_books.svg/1024px-Wikimedia_in_Education_illustration_books.svg.png"
export const EDUIMG_4 = "https://cdni.iconscout.com/illustration/premium/thumb/growth-of-education-with-hard-work-2158676-1816228.png"
export const EDUIMG_5 = "https://media.istockphoto.com/id/1409407973/vector/people-with-check-mark-make-choice.jpg?s=612x612&w=0&k=20&c=nyAG50fozvQVSKD3x6YMBo3k4t80I4fUgAuZflWhyWc="
export const EDUIMG_6 = "https://media.istockphoto.com/id/1267267142/vector/small-people-stand-next-to-a-large-to-do-list.jpg?s=612x612&w=0&k=20&c=ElNGNaGjFgjkKdqlUzSsBD9R7fdHOwmYYaiZKDQBJyA="
export const URL = process.env.API_URL
export const EDUCATION_ENDPOINT = "/educations"
export const SKILL_EDNPOINT = "/skills"
export const EDUCATION_ALT = "education-alt"
export const PROJECT_ALT = "project-alt"
export const GITHUB_REPOSITORY = "Github Repository"
export const DEPLOYED_URL = "Demo"
export const BLANK = "_blank"
export const PROJECT_HEADING = "<Project />"
export const PROJECT_REF = "project"
export const PROJECT_ENDPOINT = "/projects"
export const EXPERIENCE_ENDPOINT = "/experiences"
export const PROJECT_IMAGE = ["https://static.vecteezy.com/system/resources/thumbnails/005/879/539/small_2x/cloud-computing-modern-flat-concept-for-web-banner-design-man-enters-password-and-login-to-access-cloud-storage-for-uploading-and-processing-files-illustration-with-isolated-people-scene-free-vector.jpg"]
export const EXPERIENCE_TITLE = "<Experience/>"
export const DEVLOPER_NAME = "Developer Name"
export const MADHURENDRA_NATH_TIWARI = "Madhurendra Nath Tiwari"
export const SOFTWARE_ENGINEER = "Software Engineer"
export const COPYRIGHT = `© ${new Date().getFullYear()}`
export const SOCIAL_LINKS = "Social Links"
export const QUICK_LINKS = "Quick Links"
export const HOME = "Home"
export const PROJECT = "Project"
export const EDUCATION = "Education"
export const EXPERIENCE = "Experience"
export const SKILL = "Skill"
export const ABOUT = "About"
export const OTHERS = "Others"
export const RANDOM_QUOTES_API_URL = process.env.RANDOM_QUOTES_API_URL || ""
export const CONTACT_IMAGE_URL = "https://cdni.iconscout.com/illustration/premium/thumb/contact-us-3483601-2912018.png"
export const CONTACT_DESC = "I am available for freelance or full-time positions. Please feel free to contact me, and let's have a conversation."
export const CONTACT_ME = "<Contact Me />"
export const CONTACT = "contact"
export const EDUCATION_TITLE = '<' + EDUCATION + '/>'
export const SKILL_TITLE = '<' + SKILL + '/>'
export const FORM_URL = 'https://getform.io/f/4a0d40e8-8d29-4e1d-a219-520384176f68';
export const TEXTAREA = "textarea"
export const SUBMIT = 'submit'
export const POST = 'post'
export const MULTI_PART_FORM_DATA = "multipart/form-data";
