
export const ICON_ALT = "icon"
export const ICON_COMPONENT = "icon-component"
export const DARK_MODE_TOGGLE_COMPONENT = "dark-mode-toggle"
export const HERO_SECTION_IMAGE = 'Hero-Section-Image'
export const RESUME_LINK = 'https://drive.google.com/file/d/1uNhCQ30gTpi5P3d38Xn8rfh4SPWyC-Qe/view?usp=sharing'
export const ICON_COMPONENT_HOME = "icon-component-home"
export const SOCIAL_MEDIA_COMPONENT = "social-medial-icons"
export const MUI_CHIP = "mui-chip"
export const ABOUT_COMPONENT = "about-component"
export const ICON_ABOUT_ALT = "about-image"
export const NAME_ANIMATION = "name-animation-test-id"
export const DEFAULT_QUOTES = "Success is not final, failure is not fatal: It is the courage to continue that counts.  – Winston Churchill"
export const EDUCATION_ENDPOINT = "/educations"
export const SKILL_ENDPOINT = "/skills"
export const EDUCATION_ALT = "education-alt"
export const PROJECT_ALT = "project-alt"
export const GITHUB_REPOSITORY = "Github Repository"
export const DEPLOYED_URL = "Demo"
export const BLANK = "_blank"
export const PROJECT_REF = "project"
export const PROJECT_ENDPOINT = "/projects"
export const HOME_ENDPOINT = "/home"
export const ABOUT_ENDPOINT = "/about"
export const EXPERIENCE_ENDPOINT = "/experiences"
export const PROJECT_IMAGE = ["https://static.vecteezy.com/system/resources/thumbnails/005/879/539/small_2x/cloud-computing-modern-flat-concept-for-web-banner-design-man-enters-password-and-login-to-access-cloud-storage-for-uploading-and-processing-files-illustration-with-isolated-people-scene-free-vector.jpg"]
export const DEVLOPER_NAME = "Madhurendra Nath Tiwari"
export const MADHURENDRA_NATH_TIWARI = "Madhurendra"
export const SOFTWARE_ENGINEER = "Software Engineer"
export const COPYRIGHT = `© ${new Date().getFullYear()}`
export const SOCIAL_LINKS = "Social Links"
export const QUICK_LINKS = "Quick Links"
export const HOME = "Home"
export const PROJECT = "Project"
export const EDUCATION = "Education"
export const EXPERIENCE = "Experience"
export const SKILL = "Skill"
export const ABOUT = "About"
export const OTHERS = "Others"
export const RANDOM_QUOTES_API_URL = process.env.RANDOM_QUOTES_API_URL || ""
export const CONTACT = "contact"
export const FORM_URL = 'https://getform.io/f/4a0d40e8-8d29-4e1d-a219-520384176f68';
export const TEXTAREA = "textarea"
export const SUBMIT = 'submit'
export const POST = 'post'
export const MULTI_PART_FORM_DATA = "multipart/form-data";
export const HIRE_ME_HREF = '#contact';
export const TERMINAL_PORTFOLIO_URL = "https://dev-madhurendra-terminal-portfolio.vercel.app/"
